version: 2

jobs:
  build:
    working_directory: ~/circleci-demo-java-spring

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch

    resource_class: small

    steps:

      - checkout # check out source code to working directory

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: eschool-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: eschool-{{ checksum "pom.xml" }}

      # run the actual tests
      - run: mvn package -Dtest=\!ScheduleControllerIntegrationTest*

      - store_test_results:
          # uploads the test metadata from the `target/surefire-reports` to CircleCI dashboard.
          path: target/surefire-reports

      - store_artifacts: # store the uberjar as an artifact
          path: target/eschool.jar
  deploy:
    docker:
      enabled: true
    resource_class: small
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b7:fd:ae:26:61:c9:e4:b6:36:6f:41:74:6a:f9:86:3c"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "nohup python3 ./deploy.py -j $CIRCLE_BUILD_NUM &; exit 0"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # only deploy once build job has completed
          filters:
            branches:
              only: master # only deploy on the master branch
